from datetime import datetime, timezone
import uuid
from sqlalchemy import Column, String, Float, Integer, DateTime, ForeignKey, Text, JSON
from sqlalchemy.orm import relationship
from backend.db.postgres import Base

def get_utc_now():
    return datetime.now(timezone.utc)

class Job(Base):
    """
    Tracks the lifecycle and configuration of individual Requirement-to-Story pipeline executions.
    """
    __tablename__ = "jobs"
    __table_args__ = {'extend_existing': True}

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    status = Column(String(50), nullable=False, default="PENDING")  # PENDING, RUNNING, HUMAN_REVIEW, COMPLETED, FAILED, MANUAL_RESOLUTION_REQUIRED
    source_type = Column(String(100), nullable=False)  # FILE, JIRA, CONFLUENCE, SHAREPOINT, GDRIVE
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)
    error_message = Column(Text, nullable=True)
    config = Column(JSON, nullable=True)  # custom runtime parameters
    meta_info = Column(JSON, nullable=True)  # document metadata, author, structure
    
    # Audit and versioning
    version_number = Column(Integer, default=1)
    execution_id = Column(String(36), nullable=True)
    pipeline_run_id = Column(String(36), nullable=True)

    # Relationships
    requirements = relationship("Requirement", back_populates="job", cascade="all, delete-orphan")
    stories = relationship("Story", back_populates="job", cascade="all, delete-orphan")
    audit_logs = relationship("AuditLog", back_populates="job", cascade="all, delete-orphan")


class Requirement(Base):
    """
    Stores individual business requirements extracted from raw content by Agent 1.
    """
    __tablename__ = "requirements"
    __table_args__ = {'extend_existing': True}

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    job_id = Column(String(36), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    content = Column(Text, nullable=False)
    actors = Column(JSON, nullable=True)
    business_rules = Column(JSON, nullable=True)
    ambiguities = Column(JSON, nullable=True)
    conflicts = Column(JSON, nullable=True)
    confidence_score = Column(Float, nullable=False, default=1.0)
    trace_id = Column(String(100), nullable=False)
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)
    
    # Audit and versioning
    version_number = Column(Integer, default=1)
    execution_id = Column(String(36), nullable=True)
    pipeline_run_id = Column(String(36), nullable=True)
    status = Column(String(50), nullable=True)

    job = relationship("Job", back_populates="requirements")


class Story(Base):
    """
    Stores validated user stories with acceptance criteria generated by the pipeline.
    """
    __tablename__ = "stories"
    __table_args__ = {'extend_existing': True}

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    job_id = Column(String(36), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    epic = Column(String(255), nullable=False)
    feature = Column(String(255), nullable=False)
    title = Column(String(255), nullable=False)
    user_story = Column(Text, nullable=False)  # As a... I want... So that...
    acceptance_criteria = Column(JSON, nullable=False)  # Given-When-Then criteria
    trace_mappings = Column(JSON, nullable=False)  # mapping back to raw requirement IDs
    validation_results = Column(JSON, nullable=True)  # validation metrics (INVEST checks, quality score)
    plain_text_summary = Column(Text, nullable=True)
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)
    
    # Audit and versioning
    version_number = Column(Integer, default=1)
    execution_id = Column(String(36), nullable=True)
    pipeline_run_id = Column(String(36), nullable=True)
    status = Column(String(50), nullable=True)

    job = relationship("Job", back_populates="stories")


class AuditLog(Base):
    """
    Captures node executions, retries, inputs, and outputs within LangGraph orchestration.
    """
    __tablename__ = "audit_logs"
    __table_args__ = {'extend_existing': True}

    id = Column(Integer, primary_key=True, autoincrement=True)
    job_id = Column(String(36), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    node_name = Column(String(100), nullable=False)
    status = Column(String(50), nullable=False)  # STARTED, COMPLETED, FAILED, RETRY
    retries = Column(Integer, default=0)
    payload = Column(JSON, nullable=True)
    message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=get_utc_now)

    job = relationship("Job", back_populates="audit_logs")


class DomainDetection(Base):
    """
    Stores structured business domain detection results.
    """
    __tablename__ = "domain_detections"
    __table_args__ = {'extend_existing': True}

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    job_id = Column(String(36), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    primary_domain = Column(String(100), nullable=False)
    secondary_domains = Column(JSON, nullable=True)
    confidence = Column(Integer, nullable=False)
    reasoning = Column(Text, nullable=True)
    
    # Audit and versioning
    version_number = Column(Integer, default=1)
    execution_id = Column(String(36), nullable=True)
    pipeline_run_id = Column(String(36), nullable=True)
    status = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)


class MasterContext(Base):
    """
    Stores the full MasterContext of the Smart Orchestrator.
    """
    __tablename__ = "master_contexts"
    __table_args__ = {'extend_existing': True}

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    job_id = Column(String(36), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    requirements = Column(JSON, nullable=True)
    actors = Column(JSON, nullable=True)
    business_rules = Column(JSON, nullable=True)
    validation_context = Column(JSON, nullable=True)
    epics = Column(JSON, nullable=True)
    features = Column(JSON, nullable=True)
    hierarchy = Column(JSON, nullable=True)
    priority = Column(JSON, nullable=True)
    coverage_report = Column(JSON, nullable=True)
    dependencies = Column(JSON, nullable=True)
    orchestrator_metadata = Column(JSON, nullable=True)
    traceability_matrix = Column(JSON, nullable=True)
    
    # Audit and versioning
    version_number = Column(Integer, default=1)
    execution_id = Column(String(36), nullable=True)
    pipeline_run_id = Column(String(36), nullable=True)
    status = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)


class StoryContextPacket(Base):
    """
    Stores individual StoryContext packets mapped to features/requirements.
    """
    __tablename__ = "story_context_packets"
    __table_args__ = {'extend_existing': True}

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    job_id = Column(String(36), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    story_id = Column(String(100), nullable=False)
    requirement_id = Column(String(100), nullable=True)
    requirement = Column(JSON, nullable=True)
    epic = Column(JSON, nullable=True)
    feature = Column(JSON, nullable=True)
    actor = Column(String(100), nullable=True)
    business_rules = Column(JSON, nullable=True)
    dependencies = Column(JSON, nullable=True)
    priority = Column(String(50), nullable=True)
    validation = Column(JSON, nullable=True)
    traceability = Column(JSON, nullable=True)
    
    # Audit and versioning
    version_number = Column(Integer, default=1)
    execution_id = Column(String(36), nullable=True)
    pipeline_run_id = Column(String(36), nullable=True)
    status = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)


class StoryZest(Base):
    """
    Stores business executive summaries (Draft and Final).
    """
    __tablename__ = "story_zests"
    __table_args__ = {'extend_existing': True}

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    job_id = Column(String(36), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    type = Column(String(50), nullable=False)  # DRAFT, FINAL
    business_goal = Column(Text, nullable=False)
    scope_summary = Column(Text, nullable=False)
    actors = Column(JSON, nullable=True)
    key_features = Column(JSON, nullable=True)
    dependencies = Column(JSON, nullable=True)
    risks = Column(JSON, nullable=True)
    coverage_metrics = Column(JSON, nullable=True)
    
    # Audit and versioning
    version_number = Column(Integer, default=1)
    execution_id = Column(String(36), nullable=True)
    pipeline_run_id = Column(String(36), nullable=True)
    status = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)


class ValidationContextModel(Base):
    """
    Stores validation contexts containing conflicts, ambiguities, etc.
    """
    __tablename__ = "validation_contexts"
    __table_args__ = {'extend_existing': True}

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    job_id = Column(String(36), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    conflicts = Column(JSON, nullable=True)
    ambiguities = Column(JSON, nullable=True)
    missing_requirements = Column(JSON, nullable=True)
    domain = Column(String(100), nullable=True)
    confidence_score = Column(Integer, nullable=True)
    retry_metadata = Column(JSON, nullable=True)
    
    # Audit and versioning
    version_number = Column(Integer, default=1)
    execution_id = Column(String(36), nullable=True)
    pipeline_run_id = Column(String(36), nullable=True)
    status = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)
